# Generated by Django 4.2.4 on 2023-08-19 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0002_request_latitude_request_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
