# Generated by Django 4.2.4 on 2023-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0003_customer_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='inventory',
            field=models.ManyToManyField(to='medifly.medication'),
        ),
    ]
