# Generated by Django 4.2.4 on 2023-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0005_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
