# Generated by Django 4.2.4 on 2023-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0006_customer_registration_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emergency_medication',
            field=models.ManyToManyField(to='medifly.medication'),
        ),
    ]
