# Generated by Django 4.2.4 on 2023-08-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0008_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='medication',
        ),
        migrations.AddField(
            model_name='request',
            name='medication',
            field=models.ManyToManyField(to='medifly.medication'),
        ),
    ]
