# Generated by Django 4.2.4 on 2023-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifly', '0011_alter_request_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0', max_length=80),
            preserve_default=False,
        ),
    ]
